### PR TITLE
Rspec 2 0

### PR DESCRIPTION
**Pull request by jschairb**
I'm trying to update this to work seamlessly w/ Ruby 1.9.2 and Rspec 2.0.  This was probably breaks backwards compatibility w/ previous versions of Rspec, but not Ruby.

I'm also getting an error about loading ActiveSupport a couple of times when I try to use this in my application, so I'm probably going to be looking into that.

### CODE REVIEW

**Comment by markbates** [comment]
Thanks Josh for upgrading this. I've merged in the changes and upgraded it to use RVM, bundler, and ActiveSupport 3+, that should solve your ActiveSupport issue. Thanks for the commit!

**Comment by jschairb** [comment]
Awesome, thanks for the merge. I love your book, by the way.  Thanks for sharing your knowledge.  I'm using Distribunaut for an internal project at Rackspace, I'll write it up when I'm done.

**Comment by markbates** [comment]
Cool! Thanks. I'd love to see a write up of what you're doing over there! Let me know when you do. Thanks again.

**Comment by jschairb** [comment]
Mark,

I hate to bother you with a problem, but I'm having, what I think is, a tiny one with Distribunaut.  I keep getting `Rinda::RequestExpiredError: Rinda::RequestExpiredError` errors when just trying to call the Distribunaut Server class from a client.  I'm pretty sure I have it configured right because I can use the Rinda stuff explicitly to use the service.

Can you point me to some troubleshooting steps?

**Comment by markbates** [comment]
Where's the error being thrown in the code?

I found one reference to it in: distribunaut / lib / distribunaut / utils / rinda.rb

it says: "# it's ok that it expired. It could be that it was never registered."

Is it being thrown somewhere else?

**Comment by jschairb** [comment]
Thank you so much for responding. I'm calling this from the console of a Padrino app.  It must be that I'm not registering it correctly.  Does it not to be in some initialization phase?  Outside of requiring distribunaut, the client has no other configuration currently.

class Device
  def core
    Distribunaut::Distributed::CoreWorker
  end
end

# irb

ruby-1.8.7-p302 > Device.core
Rinda::RequestExpiredError: Rinda::RequestExpiredError
    from (druby://localhost:51878) /.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rinda/tuplespace.rb:528:in `block in read'
    from (druby://localhost:51878) /.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
    from (druby://localhost:51878) /.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rinda/tuplespace.rb:525:in `read'
    from (druby://localhost:51878) /.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1558:in`perform_without_block'
    from (druby://localhost:51878) /.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1518:in `perform'
    from (druby://localhost:51878) /.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1592:in`block (2 levels) in main_loop'
    from (druby://localhost:51878) /.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in `loop'
    from (druby://localhost:51878) /.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/drb/drb.rb:1588:in`block in main_loop'
    from /.rvm/gems/ruby-1.8.7-p302/gems/distribunaut-0.3.0/lib/distribunaut/utils/rinda.rb:34:in `read'
    from /.rvm/gems/ruby-1.8.7-p302/gems/distribunaut-0.3.0/lib/distribunaut/distributed.rb:6:in`const_missing'
    from /src/rack/crust/api/devices/app/models/device.rb:61:in `core'

**Comment by markbates** [comment]
I'm going to guess that the client can't see the ring server. In your client's console try the following:

Distribunaut::Utils::Rinda.available_services

That should give you a list of available services on the ring server. If that blows up then your client can't see the ring server, and then it's an issue of make sure you have firewalls, services, etc... all set up correctly.

**Comment by jschairb** [comment]
I had pasted a really long reply of stack traces and irb sessions until I realized that I never called DRb.start_service on the client. :\

Ok, then.... </backs-away-sheepishly>

Thanks for your help.

**Comment by markbates** [comment]
HA! Well, that would do it! Good luck.

**Pull request merged**
